version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/new_employee_assistant
  - source: /.env
    destination: /home/ubuntu/new_employee_assistant
  file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/new_employee_assistant
    pattern: '**'
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: scripts/after_deploy.sh
      timeout: 100
      runas: root